name: student_activity_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # Menggunakan rentang versi yang lebih umum

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  intl: ^0.19.0
  provider: ^6.1.2 # Untuk State Management Global
# ... (dependencies Anda yang lain)
  fl_chart: ^0.68.0 # Tambahkan baris ini
  flutter_staggered_grid_view: ^0.7.0 # Untuk layout dashboard yang menarik
  
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  # Konfigurasi ikon dipindahkan ke bawah, hanya dependency-nya yang di sini
  flutter_launcher_icons: "^0.13.1"

# Ini adalah bagian yang dipindahkan dan diperbaiki
# Pastikan bagian ini TIDAK ADA spasi di depannya (sejajar dengan 'name', 'dependencies', dll.)
flutter_launcher_icons:
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # Aset harus menggunakan garis miring '/' dan indentasi yang benar
  assets:
    - assets/images/novi.jpg